name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  mix_test:
    name: mix test (Elixir ${{matrix.elixir}} | Erlang/OTP ${{matrix.otp}})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: 1.11.1
            otp: 21.3.8.17
            warnings-as-errors: true
          - elixir: 1.11.4
            otp: 23.3
            warnings-as-errors: true
          - elixir: 1.12.0
            otp: 24.0
            warnings-as-errors: true
          - elixir: 1.13.4
            otp: 24.0
            warnings-as-errors: true
          - elixir: 1.13.4
            otp: 25.0
            check_formatted: true
            warnings-as-errors: true
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Install Dependencies
        run: |
          mix local.hex --force
          mix local.rebar --force
          mix deps.get --only test
      - run: mix compile --warnings-as-errors
        if: matrix.warnings_as_errors
      - run: mix format --check-formatted
        if: matrix.check_formatted
      - run: mix test
